python:
  # - 3.9
  - 3.10
  # - 3.11
  # - 3.12  # [not aarch64]
MACOSX_SDK_VERSION:         # [osx and x86_64]
  - "10.13"                 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:   # [osx and x86_64]
  - "10.13"                 # [osx and x86_64]