name: lintdb-cmake
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - conda-build
  - anaconda-client
  - faiss-cpu
  - pytorch::pytorch
  - conda-forge::numpy
  - pytest
  - pip:
    - chardet