name: Build and Test Cmake
on: 
  - pull_request

jobs:
  cmake-build:
    name: Run Cmake
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: install clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18 all
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          # This is useful to avoid https://github.com/microsoft/vcpkg/issues/25349
          # which is caused by missing Git history on the vcpkg submodule which ports 
          # try to access. 
          # Do not use if not needed, since it slows down the checkout of sources.
          fetch-depth: 1
      - name: submodule init
        run: |
          git submodule update --init --recursive
      - uses: lukka/get-cmake@latest
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Install Dependencies
        env:
          CC: clang-18
          CXX: clang++-18
          CMAKE_C_COMPILER: clang-18
          CMAKE_CXX_COMPILER: clang++-18
        run: |
          echo "CXX=${CXX}"
          pip install pytest numpy
          sudo apt install libopenblas-openmp-dev liblapack-dev
          sudo apt-get remove clang-14 clang-15
          sudo rm /usr/bin/clang++
          sudo ln -s /usr/bin/clang++-18 /usr/bin/clang++
          pip install .

      - name: Build
        run: |
          mkdir build && cd build \
          && conan profile new default --detect \
          && conan install .. --build=missing -s build_type=Release -s build_tests=True \
          && conan build ..
      - name: Run Tests
        run: |
          cd ./build/Release/tests \
          && ctest --output-on-failure lintdb-tests
      - name: Run Python Tests
        run: |
          pytest lintdb/python/tests  

