name: Build and upload conda packages

on:
  release:
    types: ['released', 'prereleased']
  workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package with Python ${{ matrix.python-version }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/my-env
            python-version: "3.10"

          - os: macos-14
            label: osx-64
            prefix: /usr/local/miniconda/envs/lintdb-build/conda-bld
            python-version: "3.10"

        # os: [macOS-latest, ubuntu-latest]
        # # python-version: ["3.8", "3.9", "3.10"]
        # python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: lukka/get-cmake@latest

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lintdb-build
          python-version: ${{ matrix.python-version }}
          # environment-file: conda/environment.yaml    # Path to the build conda environment
          use-mamba: true
          mamba-version: "*"
          channels: conda-forge,pytorch,defaults
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CONDA }}/envs
            conda-${{ runner.os }}--${{ runner.arch }}-build-cache
            /vcpkg-binary-cache
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('conda/environment.yaml') }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache

      - name: Update environment
        run:
          mamba env update -n lintdb-build -f
          conda/environment.yaml
        if: steps.cache.outputs.cache-hit != 'true'
      
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      # - name: Setup Conda
      #   shell: bash -l {0}
      #   run: |
      #     conda env create -f conda/environment.yaml -n lintdb-build
      #     conda activate lintdb-build
      # - name: Setup vcpkg
      #   uses: lukka/run-vcpkg@v11
      #   id: runvcpkg
      #   with:
      #     # This one is not needed, as it is the default value anyway.
      #     # vcpkgDirectory: '${{ github.workspace }}/vcpkg'
      #     vcpkgDirectory: '${{ github.workspace }}/tools/vcpkg'
      #     vcpkgJsonGlob: 'vcpkg.json'
      # - name: Run CMake
      #   uses: lukka/run-cmake@v10
      #   id: runcmake

      # - name: Build and upload the conda packages
      #   uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
      #   with:
      #     meta_yaml_dir: conda/lintdb
      #     python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
      #     upload: false
          # user: uibcdf
          # label: auto
          # token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the right name of your secret

      - name: Conda Build
        id: packages-compilation
        shell: bash -l {0}
        working-directory: ./conda
        env:
          VCPKG_DEFAULT_BINARY_CACHE: /vcpkg-binary-cache
        run: |
          conda activate lintdb-build
          out_dir=`mktemp -d -t compilation-XXXXXXXXXX`
          echo "::group::Building conda package for host platform"
          echo "conda build lintdb --no-anaconda-upload --cache-dir "conda-${{ runner.os }}--${{ runner.arch }}-build-cache" --output-folder $out_dir --python ${{ matrix.python-version }}"
          conda build lintdb --no-anaconda-upload --cache-dir "conda-${{ runner.os }}--${{ runner.arch }}-build-cache" --output-folder $out_dir --python ${{ matrix.python-version }}
          echo "::set-output name=out_dir::'$out_dir'"
          echo "::endgroup::"
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: conda-build-dir
          path: /usr/local/miniconda/envs/lintdb-build/conda-bld/lintdb-pkg_*/work/tools/vcpkg/buildtrees/*/install-x64-osx-*-out.log
          retention-days: 1
          overwrite: true
      - name: Packages uploading
        id: packages-uploading
        env:
          SHOULD_OVERWRITE: false
          UPLOAD_TOKEN: ${{secrets.ANACONDA_TOKEN}}
          UPLOAD_USER: deployql
        shell: bash -l {0}
        working-directory: conda/lintdb
        run: |
          echo "::group::Conda packages uploading"
          #cd ${{ steps.packages-compilation.outputs.out_dir }}
          label=""
          force=""
          if "$SHOULD_OVERWRITE"; then
            force="--force"
          fi
            if [ "${{github.event.action}}" == "released" ]; then
              label="main"
            elif [ "${{github.event.action}}" == "prereleased" ]; then
              label="dev"
            else
              echo "The trigger type ${{github.event.action}} is not compatible with `label: auto`"
              exit 1
            fi
          export ANACONDA_API_TOKEN=$UPLOAD_TOKEN
          SHORT_SHA="$(git rev-parse --short $GITHUB_SHA)"
          for dirname in ${{ steps.packages-compilation.outputs.out_dir }}/*; do
            if [ -d "$dirname" ]; then
              for filename in $dirname/*; do
                if [ "${filename: -8}" == ".tar.bz2" ]; then
                  echo "anaconda upload --user $UPLOAD_USER $force --label $label $filename"
                  anaconda upload --user $UPLOAD_USER $force --label $label $filename
                fi
              done
            fi
          done 
          echo "::endgroup::"
