name: Build and Test Cmake
on: 
  - pull_request

jobs:
  cmake-build:
    name: Run Cmake
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: install clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18 all
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          # This is useful to avoid https://github.com/microsoft/vcpkg/issues/25349
          # which is caused by missing Git history on the vcpkg submodule which ports 
          # try to access. 
          # Do not use if not needed, since it slows down the checkout of sources.
          fetch-depth: 1
      - name: submodule init
        run: |
          git submodule update --init --recursive
      - uses: lukka/get-cmake@latest
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          # This one is not needed, as it is the default value anyway.
          vcpkgDirectory: '${{ github.workspace }}/tools/vcpkg'
          vcpkgJsonGlob: '**/cmakepresets/vcpkg.json'

      - name: Prints output of run-vcpkg's action.
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "
      - name: Run CMake+vcpkg+Ninja
        uses: lukka/run-cmake@v10
        id: runcmake
        env:
          CC: clang-18
          CXX: clang++-18
          CMAKE_C_COMPILER: clang-18
          CMAKE_CXX_COMPILER: clang++-18
          MKLROOT: ${{ github.workspace }}/builds/debug/vcpkg_installed/x64-linux/lib/intel64
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePresetAdditionalArgs: "['-DOpenMP_CXX_FLAGS=-fopenmp=libiomp5', '-DOpenMP_CXX_LIB_NAMES=libiomp5', '-DOpenMP_libiomp5_LIBRARY=${{ github.workspace }}/builds/debug/vcpkg_installed/x64-linux/lib/intel64/libiomp5.so']"
          configurePreset: 'debug'
          buildPreset: 'debug'
          testPreset: 'debug'
          testPresetCmdString:  "['lintdb-tests', '--test-dir', 'builds/debug', '--output-on-failure']"

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install Dependencies
        run: |
          sudo apt-get install libomp-18-dev
          pip install pytest numpy
          pip install .
      - name: Run Tests
        run: |
          pytest lintdb/python/tests  

