name: Build/Publish Develop Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18 all
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: submodule init
        run: |
          git submodule update --init --recursive
      - uses: lukka/get-cmake@latest
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install Dependencies
        env:
          CC: clang-18
          CXX: clang++-18
          CMAKE_C_COMPILER: clang-18
          CMAKE_CXX_COMPILER: clang++-18
        run: |
          pip install mkdocs-material
          pip install mkdocstrings[python] markdown-callouts mkdocs-literate-nav mike
          
          sudo apt-get remove clang-14 clang-15
          sudo rm /usr/bin/clang++
          sudo ln -s /usr/bin/clang++-18 /usr/bin/clang++
          pip install .
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "docs.deploy@example.co.uk"
      - name: Build Docs Website
        run: mike deploy --push develop