name: Build and upload conda packages

on:
  release:
    types: ['released', 'prereleased']
  workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package with Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lintdb-build
          python-version: ${{ matrix.python-version }}
          environment-file: conda/environment.yaml    # Path to the build conda environment
          mamba-version: "*"
          channels: conda-forge,pytorch,defaults
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      # - name: Setup Conda
      #   shell: bash -l {0}
      #   run: |
      #     conda env create -f conda/environment.yaml -n lintdb-build
      #     conda activate lintdb-build
      # - name: Setup vcpkg
      #   uses: lukka/run-vcpkg@v11
      #   id: runvcpkg
      #   with:
      #     # This one is not needed, as it is the default value anyway.
      #     # vcpkgDirectory: '${{ github.workspace }}/vcpkg'
      #     vcpkgDirectory: '${{ github.workspace }}/tools/vcpkg'
      #     vcpkgJsonGlob: 'vcpkg.json'
      # - name: Run CMake
      #   uses: lukka/run-cmake@v10
      #   id: runcmake
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: conda/lintdb
          python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
          upload: false
          # user: uibcdf
          # label: auto
          # token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the right name of your secret
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: conda-build-dir
          path: /usr/local/miniconda/envs/lintdb-build/conda-bld/lintdb-pkg_*/work/tools/vcpkg/buildtrees/flatbuffers/install-x64-osx-rel-out.log
          retention-days: 1
          overwrite: true
