# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.1').lstrip('v') %}
{% set suffix = "_nightly" if environ.get('PACKAGE_TYPE') == 'nightly' else "" %}
{% set number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: lintdb-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/DeployQL/lintdb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A multi-vector database for token level interaction.

source:
  git_url: ../../

outputs:
  - name: liblintdb
    script: build-lib.sh  # [x86_64 and not win and not osx]
    script: build-lib-osx.sh  # [x86_64 and osx]
    script: build-lib-osx.sh # [osx-64]
    script: build-lib-arm64.sh  # [not x86_64]
    script: build-lib-arm64.sh # [osx-arm64]
    script: build-lib.bat  # [win]
    build:
      string: "h{{ PKG_HASH }}_{{ number }}_cpu{{ suffix }}"
      script_envs:
        - CFLAGS=-march=apple-a14 -mcpu=cortex-a9 -mfloat-abi=hard
      run_exports:
        - {{ pin_compatible('liblintdb', exact=True) }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('fortran')}}
        - conda-forge::fortran-compiler #[linux64]
        - conda-forge::gfortran #[linux64]
        - conda-forge::libgcc-ng # [linux64]
        - conda-forge::libstdcxx-ng # [linux64]
        - llvm-openmp  # [osx]
        - cmake >=3.23.1
        - make  # [not win]
        - openblas
        - conda-forge::swig >=4.0.2
        - numpy
      host:
        - openblas
      run:
        - openblas 
    test:
      requires:
        - conda-build
      commands:
        - test -f $PREFIX/lib/liblintdb$SHLIB_EXT       # [not win]
        - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
        - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

  - name: lintdb
    script: build-pkg.sh  # [x86_64 and not win and not osx]
    script: build-pkg-osx.sh  # [x86_64 and osx]
    script: build-pkg-osx.sh # [osx-64]
    script: build-pkg-arm64.sh # [not x86_64]
    script: build-lib-arm64.sh # [osx-arm64]
    script: build-pkg.bat  # [win]
    build:
      string: "py{{ PY_VER }}_h{{ PKG_HASH }}_{{ number }}_cpu{{ suffix }}"
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('fortran')}}
        - conda-forge::fortran-compiler #[linux64]
        - conda-forge::gfortran #[linux64]
        - conda-forge::libgcc-ng # [linux64]
        - conda-forge::libstdcxx-ng # [linux64]
        - openblas
        - sysroot_linux-64 =2.17 # [linux64]
        - conda-forge::swig >= 4.0.2
        - numpy
        - cmake >=3.23.1
        - make  # [not win]
      host:
        - python {{ python }}
        - numpy >=1.19,<2
        - {{ pin_subpackage('liblintdb', exact=True) }}
      run:
        - python {{ python }}
        - numpy >=1.19,<2
        - packaging
        - {{ pin_subpackage('liblintdb', exact=True) }}
    test:
      requires:
        - numpy
        - pytorch
      commands:
        - python -X faulthandler -m unittest discover -v -s tests/ -p "test_*"
        - sh test_cpu_dispatch.sh  # [linux64]
      files:
        - test_cpu_dispatch.sh  # [linux64]
      source_files:
        - tests