{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.1').lstrip('v') %}
{% set suffix = "_nightly" if environ.get('PACKAGE_TYPE') == 'nightly' else "" %}
{% set number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: lintdb-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/DeployQL/lintdb
  license: Apache 2
  license_family: Apache
  license_file: LICENSE
  summary: A multi-vector database for token level interaction.
  description: |
    LintDB is a multi-vector database meant for Gen AI. LintDB natively supports late interaction like colBERT and PLAID. 

source:
  git_url: ../../

outputs:
  - name: lintdb
    script: build-pkg.sh
    build:
      string: "py{{ PY_VER }}_h{{ PKG_HASH }}_{{ number }}_cpu{{ suffix }}"
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('fortran')}}
        - sysroot_linux-64 =2.17 # [linux64]
        - numpy==1.26.4
        - scikit-build-core
        - cmake >=3.25
        - make  # [not win]
        - mkl-devel =2023.0.0  # [x86_64]
        - openblas  # [not x86_64]
        - python {{ python }}
      host:
        - python {{ python }}
        - numpy==1.26.4
        - scikit-build-core
        - intel::intel-openmp =2023.0.0 
        - mkl =2023.0.0  # [x86_64]
        - openblas  # [not x86_64]
      run:
        - python {{ python }}
        - numpy==1.26.4
        - packaging
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]
    test:
      requires:
        - pytest
        - numpy==1.26.4
      commands:
        - pytest lintdb/python/tests
      source_files:
        - lintdb/python/tests